include:
  - infra-dev.yaml

services:
  api:
    build:
      dockerfile: ./Dockerfile
      target: api
    env_file: "./dev.env"
    ports:
      - "8888:8888"
  builder:
    build:
      dockerfile: ./Dockerfile
      target: builder
    env_file: "./dev.env"
