# DEVELOPMENT ONLY!

services:
  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # setup wordpress here so we have something to proxy (don't care that it's not secure here... )
  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: true
      WORDPRESS_DEBUG_LOG: true
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MARIADB_ROOT_PASSWORD: development
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    restart: unless-stopped
    ports:
      - '8036:80'
    environment:
      PMA_USER: root
      PMA_PASSWORD: development
      PMA_HOST: db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  wordpress:
  mariadb_data:
  redis_data: